import { EditorView } from '@codemirror/view';

export const tableTheme = EditorView.theme({
    '&.q-md-table-interaction > .cm-scroller > .cm-cursorLayer': {
        display: 'none',
    },
    '&.q-md-table-interaction > .cm-scroller > .cm-selectionLayer': {
        display: 'none',
    },
    '.q-md-table-widget': {
        display: 'block',
        position: 'relative',
        width: '100%',
        boxSizing: 'border-box',
        paddingBlock: 'var(--q-space-12)',
        fontFamily: 'var(--q-editor-font-family)',
        fontSize: 'var(--q-editor-font-size)',
        lineHeight: 'var(--q-editor-line-height)',
        color: 'var(--q-editor-text)',
        userSelect: 'none',
        pointerEvents: 'none',
    },
    '.q-md-table-shell': {
        display: 'grid',
        gridTemplateColumns: 'minmax(0, 1fr) var(--q-space-20)',
        width: '100%',
        maxWidth: '100%',
        boxSizing: 'border-box',
        pointerEvents: 'none',
    },
    '.q-md-table-scroll': {
        gridColumn: '1',
        gridRow: '1',
        minWidth: '0',
        overflowX: 'auto',
        overflowY: 'hidden',
        pointerEvents: 'auto',
        cursor: 'default',
    },
    '.q-md-table-layout': {
        position: 'relative',
        display: 'grid',
        gridTemplateColumns: 'auto 1fr',
        gridTemplateRows: 'auto 1fr',
        columnGap: 'var(--q-gap-xs)',
        rowGap: 'var(--q-gap-xs)',
        width: 'max(100%, var(--q-md-table-layout-min-width))',
        pointerEvents: 'auto',
    },
    '.q-md-table-corner': {
        gridColumn: '1',
        gridRow: '1',
        width: 'var(--q-space-24)',
        minHeight: 'var(--q-space-24)',
    },
    '.q-md-table-col-strip': {
        gridColumn: '2',
        gridRow: '1',
        display: 'flex',
        minWidth: '0',
    },
    '.q-md-table-body': {
        gridColumn: '1 / 3',
        gridRow: '2',
        display: 'grid',
        gridTemplateColumns: 'auto 1fr',
        columnGap: 'var(--q-gap-xs)',
        minWidth: '0',
    },
    '.q-md-table-row-strip': {
        gridColumn: '1',
        display: 'flex',
        flexDirection: 'column',
    },
    '.q-md-table-table-host': {
        gridColumn: '2',
        position: 'relative',
        minWidth: '0',
    },
    '.q-md-table-strip-btn': {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        padding: '0 var(--q-space-4)',
        minWidth: 'var(--q-space-24)',
        minHeight: 'var(--q-space-24)',
        border: 'none',
        borderRadius: 'var(--q-radius-sm)',
        background: 'transparent',
        color: 'var(--q-text-tertiary)',
        font: 'inherit',
        fontSize: 'var(--q-font-size-ui-sm)',
        cursor: 'grab',
        userSelect: 'none',
    },
    '.q-md-table-widget.q-md-table-strip-dragging, .q-md-table-widget.q-md-table-strip-dragging .q-md-table-strip-btn': {
        cursor: 'grabbing',
    },
    '.q-md-table-strip-btn:hover': {
        backgroundColor: 'var(--q-bg-surface-hover)',
        color: 'var(--q-text-secondary)',
    },
    '.q-md-table-col-strip-btn': {
        flex: '0 0 auto',
        boxSizing: 'border-box',
    },
    '.q-md-table-row-strip-btn': {
        flex: '0 0 auto',
        position: 'relative',
    },
    '.q-md-table-editor': {
        width: '100%',
        tableLayout: 'fixed',
        borderCollapse: 'collapse',
        margin: '0',
        font: 'inherit',
    },
    '.q-md-table-editor td': {
        border: 'var(--q-border-1) solid var(--q-editor-table-border)',
        padding: 'var(--q-editor-table-cell-padding)',
        verticalAlign: 'top',
        font: 'inherit',
    },
    '.q-md-table-cell': {
        cursor: 'text',
    },
    '.q-md-table-cell-wrapper': {
        overflowWrap: 'anywhere',
        wordBreak: 'break-word',
        whiteSpace: 'pre-wrap',
        minHeight: '1.2em',
        userSelect: 'none',
    },
    '.q-md-table-selection-overlay': {
        position: 'absolute',
        pointerEvents: 'none',
        zIndex: '2',
        backgroundColor: 'var(--q-editor-table-selection-bg)',
        border: 'var(--q-border-2) solid var(--q-border-accent)',
        boxSizing: 'border-box',
    },
    '.q-md-table-strip-drop': {
        position: 'absolute',
        pointerEvents: 'none',
        zIndex: '3',
        backgroundColor: 'var(--q-bg-accent)',
        borderRadius: 'var(--q-radius-full)',
    },
    '.q-md-table-resize-line': {
        position: 'absolute',
        pointerEvents: 'none',
        zIndex: '4',
        backgroundColor: 'var(--q-bg-accent)',
        borderRadius: 'var(--q-radius-full)',
    },
    '.q-md-table-resize-line[data-axis="row"]': {
        height: 'var(--q-border-2)',
    },
    '.q-md-table-resize-line[data-axis="col"]': {
        width: 'var(--q-border-2)',
    },
    '.q-md-table-widget.q-md-table-border-resizing-row, .q-md-table-widget.q-md-table-border-resizing-row *': {
        cursor: 'row-resize',
    },
    '.q-md-table-widget.q-md-table-border-resizing-col, .q-md-table-widget.q-md-table-border-resizing-col *': {
        cursor: 'col-resize',
    },
    '.q-md-table-strip-drop[data-valid="false"]': {
        backgroundColor: 'var(--q-text-muted)',
        opacity: 'var(--q-opacity-60)',
    },
    '.q-md-table-widget.q-md-table-strip-drop-invalid': {
        cursor: 'not-allowed',
    },
    '.q-md-table-strip-drop[data-axis="row"]': {
        height: 'var(--q-border-2)',
    },
    '.q-md-table-strip-drop[data-axis="col"]': {
        width: 'var(--q-border-2)',
    },
    '.q-md-table-add-row, .q-md-table-add-col': {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        opacity: '0',
        pointerEvents: 'auto',
        backgroundColor: 'var(--q-editor-table-add-bg)',
        border: '1px solid var(--q-editor-table-add-border)',
        color: 'var(--q-editor-table-handle)',
        userSelect: 'none',
        boxSizing: 'border-box',
    },
    '.q-md-table-add-icon': {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        width: 'var(--q-space-16)',
        height: 'var(--q-space-16)',
        flex: '0 0 auto',
        pointerEvents: 'none',
    },
    '.q-md-table-add-icon svg': {
        width: '100%',
        height: '100%',
        display: 'block',
    },
    '.q-md-table-widget:hover .q-md-table-add-row, .q-md-table-widget:hover .q-md-table-add-col': {
        opacity: '1',
    },
    '.q-md-table-add-row': {
        width: 'var(--q-md-table-band-width, 100%)',
        height: 'var(--q-space-20)',
        borderTop: 'none',
        cursor: 'pointer',
    },
    '.q-md-table-add-col': {
        gridColumn: '2',
        gridRow: '1',
        alignSelf: 'start',
        width: 'var(--q-space-20)',
        borderInlineStart: 'none',
        cursor: 'pointer',
    },
});
